export const ocrResources = {
  tr: { translation: { ocr: { badge: 'ÜCRETSİZ OCR', localNote: 'Belge tarayıcıda işlenir; ücretli OCR API kullanılmaz.', errorTitle: 'Belge okunamadı', errorBody: 'Belge yeterince net olmayabilir. Daha net bir fotoğraf veya farklı bir PDF ile tekrar dene.', nativeTitle: 'Mobil OCR için geliştirme sürümü gerekli', nativeBody: 'Expo Go özel cihaz-içi OCR modüllerini çalıştırmaz. iPhone ve Android için ücretsiz cihaz-içi OCR development build ile eklenecek.', retry: 'Tekrar dene' } } },
  en: { translation: { ocr: { badge: 'FREE OCR', localNote: 'The document is processed in the browser; no paid OCR API is used.', errorTitle: 'Document could not be read', errorBody: 'The document may not be clear enough. Try a sharper photo or another PDF.', nativeTitle: 'A development build is required for mobile OCR', nativeBody: 'Expo Go cannot load custom on-device OCR modules. Free on-device OCR for iPhone and Android will run in a development build.', retry: 'Try again' } } },
  es: { translation: { ocr: { badge: 'OCR GRATIS', localNote: 'El documento se procesa en el navegador; no se usa una API OCR de pago.', errorTitle: 'No se pudo leer el documento', errorBody: 'El documento puede no estar suficientemente claro. Prueba con una foto más nítida u otro PDF.', nativeTitle: 'El OCR móvil requiere una compilación de desarrollo', nativeBody: 'Expo Go no puede cargar módulos OCR nativos personalizados. El OCR gratuito en el dispositivo para iPhone y Android funcionará con una compilación de desarrollo.', retry: 'Reintentar' } } },
  pt: { translation: { ocr: { badge: 'OCR GRÁTIS', localNote: 'O documento é processado no navegador; nenhuma API OCR paga é usada.', errorTitle: 'Não foi possível ler o documento', errorBody: 'O documento pode não estar nítido o suficiente. Tente uma foto mais clara ou outro PDF.', nativeTitle: 'O OCR móvel requer uma build de desenvolvimento', nativeBody: 'O Expo Go não carrega módulos OCR nativos personalizados. O OCR gratuito no dispositivo para iPhone e Android funcionará em uma build de desenvolvimento.', retry: 'Tentar novamente' } } },
  fr: { translation: { ocr: { badge: 'OCR GRATUIT', localNote: 'Le document est traité dans le navigateur ; aucune API OCR payante n’est utilisée.', errorTitle: 'Impossible de lire le document', errorBody: 'Le document manque peut-être de netteté. Essayez une photo plus claire ou un autre PDF.', nativeTitle: 'Une version de développement est requise pour l’OCR mobile', nativeBody: 'Expo Go ne peut pas charger de modules OCR natifs personnalisés. L’OCR gratuit sur appareil pour iPhone et Android fonctionnera avec une version de développement.', retry: 'Réessayer' } } },
  de: { translation: { ocr: { badge: 'KOSTENLOSE OCR', localNote: 'Das Dokument wird im Browser verarbeitet; es wird keine kostenpflichtige OCR-API verwendet.', errorTitle: 'Dokument konnte nicht gelesen werden', errorBody: 'Das Dokument ist möglicherweise nicht scharf genug. Versuche ein klareres Foto oder eine andere PDF-Datei.', nativeTitle: 'Für mobile OCR ist ein Development Build erforderlich', nativeBody: 'Expo Go kann keine benutzerdefinierten nativen OCR-Module laden. Kostenlose OCR auf iPhone und Android läuft in einem Development Build.', retry: 'Erneut versuchen' } } },
  ar: { translation: { ocr: { badge: 'OCR مجاني', localNote: 'تتم معالجة المستند في المتصفح ولا يتم استخدام واجهة OCR مدفوعة.', errorTitle: 'تعذر قراءة المستند', errorBody: 'قد لا يكون المستند واضحًا بما يكفي. جرّب صورة أوضح أو ملف PDF آخر.', nativeTitle: 'يتطلب OCR على الهاتف نسخة تطوير', nativeBody: 'لا يمكن لـ Expo Go تحميل وحدات OCR أصلية مخصصة. سيعمل OCR المجاني على iPhone وAndroid عبر نسخة تطوير.', retry: 'إعادة المحاولة' } } },
  ru: { translation: { ocr: { badge: 'БЕСПЛАТНЫЙ OCR', localNote: 'Документ обрабатывается в браузере; платный OCR API не используется.', errorTitle: 'Не удалось прочитать документ', errorBody: 'Документ может быть недостаточно чётким. Попробуйте более качественное фото или другой PDF.', nativeTitle: 'Для мобильного OCR нужна development-сборка', nativeBody: 'Expo Go не загружает пользовательские нативные OCR-модули. Бесплатный OCR на устройстве для iPhone и Android будет работать в development-сборке.', retry: 'Повторить' } } },
  hi: { translation: { ocr: { badge: 'मुफ़्त OCR', localNote: 'दस्तावेज़ ब्राउज़र में प्रोसेस होता है; कोई भुगतान वाला OCR API उपयोग नहीं होता।', errorTitle: 'दस्तावेज़ पढ़ा नहीं जा सका', errorBody: 'दस्तावेज़ पर्याप्त साफ़ नहीं हो सकता। अधिक स्पष्ट फोटो या दूसरा PDF आज़माएँ।', nativeTitle: 'मोबाइल OCR के लिए डेवलपमेंट बिल्ड आवश्यक है', nativeBody: 'Expo Go कस्टम ऑन-डिवाइस OCR मॉड्यूल लोड नहीं कर सकता। iPhone और Android पर मुफ़्त ऑन-डिवाइस OCR डेवलपमेंट बिल्ड में चलेगा।', retry: 'फिर कोशिश करें' } } },
  id: { translation: { ocr: { badge: 'OCR GRATIS', localNote: 'Dokumen diproses di browser; tidak menggunakan API OCR berbayar.', errorTitle: 'Dokumen tidak dapat dibaca', errorBody: 'Dokumen mungkin kurang jelas. Coba foto yang lebih tajam atau PDF lain.', nativeTitle: 'OCR seluler memerlukan development build', nativeBody: 'Expo Go tidak dapat memuat modul OCR native khusus. OCR gratis di perangkat untuk iPhone dan Android akan berjalan melalui development build.', retry: 'Coba lagi' } } },
  'zh-CN': { translation: { ocr: { badge: '免费 OCR', localNote: '文档在浏览器中处理，不使用付费 OCR API。', errorTitle: '无法读取文档', errorBody: '文档可能不够清晰，请尝试更清晰的照片或其他 PDF。', nativeTitle: '移动端 OCR 需要开发版本', nativeBody: 'Expo Go 无法加载自定义原生 OCR 模块。iPhone 和 Android 的免费端侧 OCR 将通过开发版本运行。', retry: '重试' } } },
} as const;
